---

- name: nextcloud
  hosts: nextcloudserver
  become: true

  vars:
    nextcloud_version: 26.0.3
    nextcloud_fqdn: localhost

    nextcloud_os_user: nextclouduser

    mariadb_root_password: XxXxXMain

    nextcloud_db_name: nextcloud
    nextcloud_db_user: nextcloud
    nextcloud_db_password: XxXxXuser
    
    nextcloud_admin_user: admin
    nextcloud_admin_password: XxXxXAdmin

    install_media: false


  roles:
    - nextcloud.server
